name: painn
channels:
  - defaults
  - conda-forge
dependencies:
  #- _libgcc_mutex=0.1=main
  - _openmp_mutex
  - asttokens=2.0.5
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.6.3
  - ipython=8.27.0
  - jedi=0.19.1
  #- ld_impl_linux-64
  - libffi=3.4.4
  #- libgcc-ng
  - libgomp
  #- libstdcxx-ng
  #- libuuid
  - matplotlib-inline=0.1.6
  #- ncurses
  - openssl=3.0.15
  - parso=0.8.3
  - pexpect=4.8.0
  - pip=24.2
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.12.3
  #- readline
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - traitlets=5.14.3
  - tzdata=2024b
  - wcwidth=0.2.5
  - wheel=0.44.0
  - xz=5.4.6
  - zlib
  - pip:
      - aiohappyeyeballs
      - aiohttp
      - aiosignal
      - attrs
      - certifi
      - charset-normalizer
      - filelock
      - frozenlist
      - fsspec
      - idna
      - jinja2
      - lightning
      - lightning-utilities
      - markupsafe
      - mpmath
      - multidict
      - networkx
      - numpy
      - nvidia-cublas-cu12
      - nvidia-cuda-cupti-cu12
      - nvidia-cuda-nvrtc-cu12
      - nvidia-cuda-runtime-cu12
      - nvidia-cudnn-cu12
      - nvidia-cufft-cu12
      - nvidia-curand-cu12
      - nvidia-cusolver-cu12
      - nvidia-cusparse-cu12
      - nvidia-nccl-cu12
      - nvidia-nvjitlink-cu12
      - nvidia-nvtx-cu12
      - packaging
      - propcache
      - psutil
      - pyparsing
      - pytorch-lightning
      - pyyaml
      - requests
      - sympy
      - torch
      - torch-geometric
      - torchmetrics
      - tqdm
      - triton
      - typing-extensions
      - urllib3
      - yarl